Added test cases
Polkadex-Substrate/polkadex-custom-assets pull request #6
Opened 2020-11-09 17:56 UTC by ksr30

2020-11-09 18:07 UTC, Gauthamastro commented on src/tests.rs
> +    let native_asset =  ("Native").using_encoded(<Test as frame_system::Trait>::Hashing::hash);
Why did you recreate native_asset here?

2020-11-09 18:14 UTC, Gauthamastro commented on src/tests.rs
> +        assert_eq!(Native::burn(250u128), PositiveImbalance::new(200u128)); //@Gautham check this
This is right!

2020-11-09 18:21 UTC, Gauthamastro requested changes

2020-11-09 18:21 UTC, Gauthamastro commented on src/tests.rs
> +    let native_asset =  ("Native").using_encoded(<Test as frame_system::Trait>::Hashing::hash);
Why did you initialize native_asset again?

2020-11-09 18:21 UTC, Gauthamastro commented on src/tests.rs
> +        assert_eq!(Native::burn(250u128), PositiveImbalance::new(200u128)); //@Gautham check this
This is all right!

2020-11-10 10:20 UTC, ksr30 commented on src/tests.rs
> +    let native_asset =  ("Native").using_encoded(<Test as frame_system::Trait>::Hashing::hash);
oops ... let me remove that

2020-11-10 10:49 UTC, ksr30 commented
![](https://github.trello.services/images/mini-trello-icon.png) [DEX-202.08 [DEV] Test Custom Asset pallet](https://trello.com/c/kvRbZAbt/37-dex-20208-dev-test-custom-asset-pallet)

2020-11-10 12:04 UTC, Gauthamastro approved these changes

2020-11-10 12:04 UTC, merged